### ISSUE TITLE
sign up for readthedocs.io

### ISSUE THREAD

**Issue by jayunit100** [aroradaman/windows-networking#1]
daman - sign up for readthedocs.io so  we are both maintainers

**Comment by aroradaman** [comment]
created a account with `aroradaman` username

**Comment by aroradaman** [comment]
@jayunit100  what should I do next ?

**Comment by jayunit100** [comment]
I'll add u as maintainer to the site in a few

**Comment by jayunit100** [comment]
Ok added u as maintainer ...check your windowsnetworking.readthedocs.io  notifications maybe in email....

NeXT

Can you click admin->integrations and try to add the github web hook integration?

Since your owner, I think you need to do it.

**Comment by aroradaman** [comment]
webhook integrated successfully !
