### ISSUE TITLE
automate builds

### ISSUE THREAD

**Issue by jayunit100** [aroradaman/windows-networking#2]
lets automate our builds of windowsnetworking.readthedocs.io ! 

- Go to the Settings page for your GitHub project
- Click Webhooks > Add webhook
- For Payload URL, use https://readthedocs.org/api/v2/webhook/windowsnetworking/245572/
found on the project’s Admin > Integrations page. You may need to prepend https:// to the URL.

- For Content type,
both application/json and application/x-www-form-urlencoded work
- Leave the Secrets field blank
- Select Let me select individual events, and
 mark Branch or tag creation,
 Branch or tag deletion,
 Pull requests
 Pushes events
- Ensure Active is enabled; it is by default
- Finish by clicking Add webhook.

You may be prompted to enter your GitHub password to confirm your action.

**Comment by aroradaman** [comment]
thanks !
automated build is working now

/close
closing this now
